### ISSUE TITLE
PHP 7.4 support?

### ISSUE THREAD

**Issue by TomasVotruba** [Webysther/composer-debian#2]
Currently all our CI are failing, because we build on this image

**Comment by epynic** [comment]
this is working fine for me, bumping the php image version also builds the image successfully.

`FROM php:7.4`

**Comment by TomasVotruba** [comment]
I use it on Gitlab CI, where you can only mention image name

**Comment by epynic** [comment]
> I use it on Gitlab CI, where you can only mention image name

You can build your own image and push.
for convenience have built the image from php:7.4
(https://hub.docker.com/r/epynic/composer-debian-php-7-4)

**Comment by TomasVotruba** [comment]
Thanks, I'm gonna try it

**Comment by webysther** [comment]
@TomasVotruba sorry for the late response, for some reason I don't receive this notification or bypass by me, as a lot of nodejs come from my feed. Fixing this. 😞

**Comment by webysther** [comment]
@TomasVotruba and @epynic  when a new PHP comes up I create a branch with this name to create and mantain a automated docker separated, the new branch php74 was created.
